[package]
name = "inshd"
version = "0.4.10"
edition = "2021"
description = "A daemon for insh."

[[bin]]
name = "inshd"
path = "src/main.rs"

[dependencies]
common = { version = "0.1.0", path = "../common" }
insh-api = { version = "0.1.0", path = "../insh-api" }
path-finder = { version = "0.1.0", path = "../path-finder" }
phrase-searcher = { version = "0.1.0", path = "../phrase-searcher" }
file-type = { version = "0.1.0", path = "../file-type" }
file-info = { version = "0.1.0", path = "../file-info" }

# Used for command line argument parsing.
clap = { workspace = true }

# Used to make the server a daemon.
daemonize = "0.5.0"

# Used for logging.
log = { workspace = true }
flexi_logger = { workspace = true }

# Used for declaring lazily evaluated static values.
lazy_static = { workspace = true }

# Provides friendly bindings for *nix platform APIs.
# Used for doing things such as sending signals to processes (to stop inshd for example).
nix = { workspace = true }

# Used for generating the builder pattern for structs.
typed-builder = { workspace = true }

# Used for deserializing requests.
bincode = { workspace = true }

# Used for globally unique identifiers.
uuid = { workspace = true }

# Used for concurrent programming.
crossbeam = { workspace = true }

# Used to handle signals.
signal-hook = { version = "0.3.15", features = ["extended-siginfo"] }

# Used to make handling pipes easier.
os_pipe = "1.1.4"

# Used to control access to persistent data stored in the file system.
fslock = "0.2.1"

# Used for serialization and deserialization of data structures.
serde = { workspace = true }
serde_yaml = { workspace = true }
