[package]
name = "til"
version = "0.1.0"
edition = "2021"

[features]
# Explicitly, the default features are none.
default = []

# The logging feature enables logging which is helpful for development.
logging = [
    "dep:log",
]

[dependencies]
rend = { version = "0.1.0", path = "../rend" }
term = { version = "0.1.0", path = "../term" }

crossterm = { workspace = true, features = ["serde"] }
serde = { workspace = true }

# Used for generating the builder pattern for structs.
typed-builder = { workspace = true }

# Used for logging. (Only included if the logging features is enabled.)
log = { workspace = true, optional = true }

# Used for globally unique identifiers.
uuid = { workspace = true }

# Used for declaring lazily evaluated static values.
lazy_static = { workspace = true }

# Used for determining platform-specific directories.
dirs = { workspace = true }

# Provides friendly bindings for *nix platform APIs.
#
# Used for:
#   - sinding terminal resizes to programs.
nix = { workspace = true }

# Used for running programs.
subprocess = "0.2.9"

# Used for concurrent programming.
crossbeam = { workspace = true }
