[package]
name = "insh"
version = "0.2.0"
edition = "2021"

[dependencies]
crossterm = "0.23.0"
regex = "1.5.4"
clap = "3.1.0"
unicode-segmentation = "1.9.0"
itertools = "0.10.3"

[dev-dependencies]
test-case = "2.0.0"
