[workspace]

members = [
    "insh",
    "inshd",
    "common",
    "insh-api",
    "til",
    "term",
    "rend",
    "path-finder",
    "phrase-searcher",
    "size",
    "file-info",
    "file-type",
    "db-client",
    "db-client/model-macro",
    "db-api",
]
