[package]
name = "highlighter"
version = "0.1.0"
edition = "2021"

[dependencies]
# Used to work out which part of some code is what.
tree-sitter-highlight = { workspace = true }

# The grammars for the languages which can be highlighted.
tree-sitter-bash = { workspace = true }
tree-sitter-c = { workspace = true }
tree-sitter-go = { workspace = true }
tree-sitter-javascript = { workspace = true }
tree-sitter-json = { workspace = true }
tree-sitter-python = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-sequel = { workspace = true }
tree-sitter-toml-ng = { workspace = true }
tree-sitter-yaml = { workspace = true }

[dev-dependencies]
# Used for parameterizing tests.
test-case = { workspace = true }
