mod u8;
pub use crate::fields::u8::U8;
mod u16;
pub use crate::fields::u16::U16;
mod u32;
pub use crate::fields::u32::U32;
mod u64;
pub use crate::fields::u64::U64;
mod str;
pub use crate::fields::str::Str;
mod datetime;
pub use crate::fields::datetime::DateTime;
