[package]
name = "insh-api"
version = "0.1.0"
edition = "2021"

[dependencies]
path-finder = { version = "0.1.0", path = "../path-finder" }
phrase-searcher = { version = "0.1.0", path = "../phrase-searcher" }
file-type = { version = "0.1.0", path = "../file-type" }
file-info = { version = "0.1.0", path = "../file-info" }

# Used for generating the builder pattern for structs.
typed-builder = { workspace = true }

# Used for serialization and deserialization of data structures.
serde = { workspace = true }

# Used for globally unique identifiers.
uuid = { workspace = true, features = ["serde"] }
