[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]

# Used for logging.
flexi_logger = { workspace = true }

# Used for declaring lazily evaluated static values.
lazy_static = { workspace = true }

# Used for determining platform-specific directories.
dirs = { workspace = true }
