#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

"${REPO_ROOT}/cargo-scripts/all"

"${REPO_ROOT}/scripts/check-with-logging-feature"

"${REPO_ROOT}/scripts/lint-arbsego"
