#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
TRUTH_FILE="${REPO_ROOT}/truth.yaml"

BASH_LIB="${REPO_ROOT}/bash-lib"
pushd "${BASH_LIB}" > /dev/null
source "${BASH_LIB}/ensure_brew_formula_installed.sh"
source "${BASH_LIB}/check_cargo_crate_installed.sh"
popd > /dev/null

ensure_brew_formula_installed yq

ARBSEGO_VERSION="$(yq '.arbsego.version' < "${TRUTH_FILE}")"

# Ensure that arbsego is installed.
# TODO: Once we push arbsego to crates.io, then make a `ensure_cargo_crate_installed` function in
# the `bash-lib` repo and use that here.
if [[ $(check_cargo_crate_installed arbsego "${ARBSEGO_VERSION}") == "no" ]]; then
    echo "Arbsego version "${ARBSEGO_VERSION}" is not installed."
    echo -n "Would you like to install it and continue? "
    install="$(ask_yes_or_no)"
    if [[ "${install}" == "no" ]]; then
        echo "Aborting..."
        exit 1
    fi
    cargo install --git https://github.com/AustinScola/arbsego.git --tag "v${ARBSEGO_VERSION}"
fi

arbsego
