[package]
name = "insh"
version = "0.4.10"
edition = "2021"

[[bin]]
name = "insh"
path = "src/main.rs"

[features]
# Explicitly, the default features are none.
default = []

# The logging feature enables logging which is helpful for development.
logging = [
    "dep:log",
    "dep:flexi_logger",
    "til/logging",
]

[dependencies]
til = { version = "0.1.0", path = "../til" }
term = { version = "0.1.0", path = "../term" }
rend = { version = "0.1.0", path = "../rend" }
common = { version = "0.1.0", path = "../common" }
insh-api = { version = "0.1.0", path = "../insh-api" }
path-finder = { version = "0.1.0", path = "../path-finder" }
phrase-searcher = { version = "0.1.0", path = "../phrase-searcher" }
file-type = { version = "0.1.0", path = "../file-type" }
file-info = { version = "0.1.0", path = "../file-info" }
human-friendly = { version = "0.1.0", path = "../human-friendly" }

crossterm = { workspace = true }
regex = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
unicode-segmentation = "1.9.0"
itertools = { workspace = true }

# Used to manage the clipboard.
copypasta = "0.10.1"

# Used for serialization and deserialization of data structures.
serde = { workspace = true }
serde_yaml = { workspace = true }

# Used for logging. (These dependencies are only included if the logging features is enabled.)
log = { workspace = true, optional = true }
flexi_logger = { workspace = true, optional = true }

# Used to create a parser for text with ANSI escape codes.
nom = "7.1.1"

# Used for generating the builder pattern for structs.
typed-builder = { workspace = true }

# Used for serializing requests.
bincode = { workspace = true }

# Used for globally unique identifiers.
uuid = { workspace = true, features = ["serde"] }

# Used for concurrent programming.
crossbeam = { workspace = true }

[dev-dependencies]
test-case = "2.0.0"
