name: Rust

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Check that it compiles
        run: ./cargo-scripts/check

  check-with-logging-feature:
    name: Check (with logging feature)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Check that it compiles with the logging feature enabled
        run: ./scripts/check-with-logging-feature
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Lint with clippy
        run: ./cargo-scripts/lint

  arbsego:
    name: Arbsego
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Install Brew
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

          # Run the commands that Brew recommends for setting itself up.
          echo '# Set PATH, MANPATH, etc., for Homebrew.' >> ~/.bash_profile
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          # Turn off Brew usage analytics.
          brew analytics off

      - name: Install yq
        run: |
          # Make sure brew is setup.
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          # Install yq using brew.
          brew install yq

      - name: Install Arbsego
        run: |-
          # Make sure brew is setup.
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          # Get the version of Arbsego to use.
          ARBSEGO_VERSION="$(yq '.arbsego.version' < truth.yaml)"
  
          # Install Arbsego using cargo.
          cargo install --git https://github.com/AustinScola/arbsego.git --tag "v${ARBSEGO_VERSION}"

      - name: Lint using Arbsego
        run: |
          # Make sure brew is setup.
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          # Lint using Arbsego.
          ./scripts/lint-arbsego

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Check formatting
        run: ./cargo-scripts/format -- --check

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Test
        run: cargo test
